name: This is my test workflow

on:
  push:
    branches:
      - main

env:
  ENVIRONMENT_NAME: develop
  STACK_NAME: myStack

jobs:
  firstJob:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v3

      - name: Checkout Custom repo
        uses: actions/checkout@v3
        with:
          repository: <github_repo>/<repo_name>
          path: repo_name
          ref: main
          token: ${{ secrets.PAT_GITHUB_TOKEN }} # Generate Personal Access Token

      # Check Dockerfile for best practices
      - name: Hadolint Action
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile
          recursive: true
          ignore: DL3013,SC2016
      
      # Prepare Docker envinronment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: <AWS::AccountId>.dkr.ecr.<AWS::Region>.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Run script
        shell: bash
        run: |
          repo_name/scripts/create_new_hotfix.sh ${{ env.STACK_NAME }} ${{ env.ENVIRONMENT_NAME }}
      
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          #context: ${{ github.workspace }}
          push: true
          tags: |
            <AWS::AccountId>.dkr.ecr.<AWS::Region>.amazonaws.com/testing_repo/my-image:latest
            <AWS::AccountId>.dkr.ecr.<AWS::Region>.amazonaws.com/testing_repo/my-image:MY_VERSION
      
      - name: Release Docker Image to ECR
        uses: docker/build-push-action@v2
        with:
          #context: ${{ github.workspace }}
          push: true
          tags: |
            <AWS::AccountId>.dkr.ecr.<AWS::Region>.amazonaws.com/testing_repo/my-image:MY_VERSION