name: Some random name

on:
  workflow_dispatch:
    inputs:
      account:
        type: choice
        description: 'AWS Account'
        required: true
        default: 'qsa-project-name'
        options:
          - accountA
          - accountB
          - accountC

env:
  AWS_ACCOUNT: ${{ github.event.inputs.account }}

jobs:
  createBuckets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup some variables
        shell: bash
        run: ./scripts/variables.sh ${{ env.AWS_ACCOUNT }}
      
#       - name: Setup additional vars
#         shell: bash
#         run: |
#           if [[ ${{ env.AWS_ACCOUNT }} == 'accountA' ]]; then
#             echo REGION='eu-west-1' >> $GITHUB_ENV
#           elif [[ ${{ env.AWS_ACCOUNT }} == 'accountB' ]]; then
#             echo REGION='us-west-2' >> $GITHUB_ENV
#           elif [[ ${{ env.AWS_ACCOUNT }} == 'accountC' ]]; then
#             echo REGION='us-east-1' >> $GITHUB_ENV
#           else
#             echo "You have provided incorrect AWS Account"
#             exit 1
#           fi
      
      - name: Test our choice
        shell: bash
        run: |
          echo "This is my region: ${{ env.REGION }}"
          echo "And this is my region too: ${REGION}"
